#!/usr/bin/env python

"""
Copyright 2018 The Johns Hopkins University Applied Physics Laboratory.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

"""
Usage:

    npy2hdf5 [datasetname] [npy_path_to_read] [hdf5_path_to_write]

For example,

    npy2hdf5 train_em mydata.npy mydata.h5

"""


import numpy as np
import h5py

import sys

_USING_STDOUT = False

try:
    data = np.load(sys.argv[-2])
except:
    _USING_STDOUT = True
    raise ValueError("Cannot read from STDIN yet.")


dtype = data.dtype

if dtype == np.uint64:
    if not _USING_STDOUT:
        print("Converting to uint8 from " + str(dtype))
    dtype = np.uint8


with h5py.File(sys.argv[-1], 'w') as fh:
    fh.create_dataset(sys.argv[-3], data=data, dtype=dtype)

