# Copyright 2019 The Johns Hopkins University Applied Physics Laboratory
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM kaixhin/cuda-theano:7.5

RUN apt-get clean
RUN apt-get update
RUN apt-get -y upgrade

# Install dependencies
RUN apt-get update && apt-get install -y \
  libhdf5-dev \
  python-h5py \
  python-yaml \
  vim 

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN apt-get -y install build-essential

RUN apt-get -y install \
  libx11-dev \
  #libblosc-dev \
  libblas-dev \
  liblapack-dev \
  wget

# Setup python packages
RUN pip install --ignore-installed Theano
RUN pip install --ignore-installed numpy 
RUN pip3 install --ignore-installed numpy
RUN pip3 install --ignore-installed awscli
RUN pip3 install --ignore-installed boto3
RUN pip install --ignore-installed SimpleITK
RUN pip install --ignore-installed enum 

# Upgrade six
RUN pip3 install --upgrade six
RUN pip install --upgrade six
RUN pip install --ignore-installed keras


# Install intern
RUN pip install blosc==1.4.4
RUN pip install intern==0.9.11
RUN mkdir -p /src/weights
RUN wget --directory-prefix /src/weights https://raw.githubusercontent.com/aplbrain/emcv/master/unets/weights/kasthuri/synapse_weights.hdf5
RUN wget --directory-prefix /src/weights https://raw.githubusercontent.com/aplbrain/emcv/master/unets/weights/kasthuri/membrane_weights.hdf5
# Create workspace
# TODO: Re-org this to use git clone and S3
WORKDIR /src
COPY ./ /src/

ENV KERAS_BACKEND=theano
ENV PATH=/src:$PATH

#BLAS FOR THEANO
RUN apt-get install -y libatlas-base-dev 
#ENV THEANO_FLAGS=blas.ldflags='-lf77blas -latlas -lgfortran'

ENV DEVICE="cuda0"
ENV GPUARRAY_CUDA_VERSION=75
ENV THEANO_FLAGS="device=cuda0,blas.ldflags='-lf77blas -latlas -lgfortran',dnn.include_path=/usr/local/cuda/include"
#ENV THEANO_FLAGS='device=cuda,lib.cnmem=1'


