FROM tensorflow/tensorflow:latest-gpu

LABEL maintainer="Jordan Matelsky <jordan.matelsky@jhuapl.edu>"

RUN apt update
RUN apt install -y git
RUN pip install scikit-image scipy numpy tensorflow-gpu h5py pillow absl-py
RUN git clone https://github.com/google/ffn/

