#!/usr/bin/env python

import glob

def get_max_checkpoint(path="/model/model.ckpt-*"):
    return max([int(f.split(".")[-2].split("-")[1]) for f in glob.glob(path)])

if __name__ == "__main__":
    print(get_max_checkpoint())
